# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet E:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files E:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet E:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.runs/dds_compiler_0_synth_1/dds_compiler_0.dcp
set_property used_in_implementation false [get_files E:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.runs/dds_compiler_0_synth_1/dds_compiler_0.dcp]

add_files E:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all e:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all E:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.srcs/sources_1/bd/system/system_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files E:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib E:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.srcs/sources_1/imports/hdl/system_wrapper.v
read_xdc E:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.srcs/constrs_1/imports/new/xdc.xdc
set_property used_in_implementation false [get_files E:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.srcs/constrs_1/imports/new/xdc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/duc/freelancer/042018/SDR/SDR_2014_2/SDR_2014_2.cache/wt [current_project]
set_property parent.project_dir E:/duc/freelancer/042018/SDR/SDR_2014_2 [current_project]
catch { write_hwdef -file system_wrapper.hwdef }
synth_design -top system_wrapper -part xc7z020clg484-1
write_checkpoint system_wrapper.dcp
report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb
